# Generated by Django 4.2.7 on 2023-11-17 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myuser', '0003_remove_myuser_nickname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='登録日'),
        ),
    ]
